root = "."
tmp_dir = ".air-tmp"

[build]
cmd = "go build -o ./.air-tmp/server ./cmd/server"
entrypoint = ["./.air-tmp/server"]
include_ext = ["go", "mod", "sum"]
exclude_dir = [".air-tmp", "vendor"]
exclude_regex = ["_test.go"]
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = 1000

[log]
time = true

[misc]
clean_on_exit = true
