FROM golang:1.27-alpine

ARG AIR_VERSION=v1.67.4

RUN apk add --no-cache gcc musl-dev
RUN go install github.com/air-verse/air@${AIR_VERSION}

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
